//! Copyright 2026 0xClandestine, Ekryski, TheTom, Ambisphaeric
//! SPDX-License-Identifier: Apache-2.0
//! CUDA codegen backend (CUDA_BACKEND_SPEC §4.2 / SCOPE Phases 1–4).
//!
//! Lowers the backend-neutral algorithm IR to CUDA C++ (compiled at
//! runtime via NVRTC, or offline via `nvcc`). Shares the IR, the
//! `#[kernel]` macro, and the entire `quant::{codec,format}` layer with
//! the Metal path — only the leaf text differs, captured in
//! [`TargetProfile`](crate::backend::TargetProfile).
//!
//! **Status: Phase 1 — elementwise smoke subset.** `generate` emits CUDA
//! C++ for `KernelMode::Elementwise` kernels using the ops
//! `ProgramId / Const / Load / Store / BinOp / UnaryOp / Cast / Fma`.
//! That covers the `copy` / `vector_add` smoke kernels end-to-end
//! (NVRTC compile + launch on the GX10 / sm_121). Reductions,
//! simdgroup/MMA, coop_tile, and `InlineMsl` return `UnsupportedOp`
//! pending Phases 2–5.
//!
//! Strategy note (SCOPE §6 — decided): do NOT fork `msl/emit_block.rs`
//! (61 KB) up front. This is a fresh, minimal op-walker for the Phase-1
//! subset; it grows per phase. A shared backend-neutral walker is only
//! extracted once both emitters exist and the common structure is
//! empirically clear — premature extraction risks the wrong abstraction
//! over a hot path.
//!
//! Phase-1 deliberate simplifications (tracked for Phase 2):
//! - No optimization passes run yet (the pipeline is backend-neutral but
//!   can introduce `FusedElementwise`/`Fma` ops the smoke walker doesn't
//!   handle). Smoke kernels emit correctly from raw IR.
//! - A trailing `unsigned int _n_elems` param + an `if (gtid >= _n_elems)
//!   return;` guard replace Metal's non-uniform-threadgroup bounds model.

use std::fmt::Write as _;

use metaltile_core::{
    dtype::DType,
    ir::{
        ActKind, BinOpKind, Block, IndexExpr, Kernel, KernelMode, Op, Param, ParamKind, ReduceKind,
        UnaryOpKind, ValueId,
    },
};

use crate::{
    Result,
    backend::{CodegenBackend, Target, TargetProfile},
    error::Error,
};

/// Shared preamble for every emitted CUDA kernel: headers, the `MT_INF`
/// constant (NVRTC has no `INFINITY` macro), and the block-scaled-quant
/// decode helpers ported verbatim from `msl/preamble.rs` (pure arithmetic
/// → identical to `quant::codec`). Unused helpers are pruned by the
/// compiler, so we always emit them.
const CUDA_PREAMBLE: &str = r#"// Generated by MetalTile (CUDA backend). DO NOT EDIT.
#include <cuda_fp16.h>
#include <cuda_bf16.h>
// +inf without pulling <math_constants.h> (NVRTC-safe). NVRTC has no
// INFINITY macro, so alias it too (kernels emit literal INFINITY for masks).
#define MT_INF (__int_as_float(0x7f800000))
#ifndef INFINITY
#define INFINITY MT_INF
#endif

// E2M1 (fp4): codebook {0,.5,1,1.5,2,3,4,6}, sign in bit 3.
__device__ __forceinline__ float mt_decode_e2m1(unsigned int code) {
    unsigned int m = code & 7u;
    float mag = (m < 1u) ? 0.0f : (m < 2u) ? 0.5f : (m < 3u) ? 1.0f : (m < 4u) ? 1.5f
              : (m < 5u) ? 2.0f : (m < 6u) ? 3.0f : (m < 7u) ? 4.0f : 6.0f;
    return (code & 8u) ? -mag : mag;
}
// E4M3 (fp8): (1+m/8)*2^(e-7); subnormal m*2^-9; sign in bit 7.
__device__ __forceinline__ float mt_decode_e4m3(unsigned int bits) {
    unsigned int e = (bits >> 3u) & 15u;
    unsigned int m = bits & 7u;
    float mag = (e < 1u) ? ((float)m * 0.001953125f)
              : ((1.0f + (float)m * 0.125f) * exp2f((float)e - 7.0f));
    return ((bits >> 7u) & 1u) ? -mag : mag;
}
// E5M2 (fp8): (1+m/4)*2^(e-15); subnormal m*2^-16; sign in bit 7.
__device__ __forceinline__ float mt_decode_e5m2(unsigned int bits) {
    unsigned int e = (bits >> 2u) & 31u;
    unsigned int m = bits & 3u;
    float mag = (e < 1u) ? ((float)m * 0.0000152587890625f)
              : ((1.0f + (float)m * 0.25f) * exp2f((float)e - 15.0f));
    return ((bits >> 7u) & 1u) ? -mag : mag;
}
// Symmetric int8: reinterpret the byte as i8 (sign-extend low 8 bits).
__device__ __forceinline__ float mt_decode_int8(unsigned int bits) {
    return (float)((int)(bits << 24u) >> 24);
}

// Neural activations (ported from msl/preamble.rs).
__device__ __forceinline__ float mt_silu(float x) { return x / (1.0f + __expf(-x)); }
__device__ __forceinline__ float mt_relu(float x) { return fmaxf(0.0f, x); }
__device__ __forceinline__ float mt_sigmoid(float x) { return 1.0f / (1.0f + __expf(-x)); }
__device__ __forceinline__ float mt_gelu(float x) {
    const float k = 0.7978845608f;
    float arg = k * (x + 0.044715f * x*x*x);
    arg = fminf(fmaxf(arg, -15.0f), 15.0f);
    return 0.5f * x * (1.0f + tanhf(arg));
}

"#;

/// Name of the synthetic element-count param appended to every emitted
/// CUDA kernel (drives the bounds guard). Chosen to not collide with DSL
/// param names.
pub const N_ELEMS_PARAM: &str = "_n_elems";

/// CUDA C++ generator. Mirror of `msl::MslGenerator` for the NVIDIA target.
#[derive(Debug, Clone)]
pub struct CudaGenerator {
    profile: TargetProfile,
}

impl Default for CudaGenerator {
    fn default() -> Self { Self::new() }
}

impl CudaGenerator {
    pub fn new() -> Self {
        CudaGenerator { profile: TargetProfile::cuda() }
    }

    /// Build a generator pinned to a specific profile (e.g. a Blackwell
    /// profile with `MmaStrategy::Tcgen05` for Phase 4).
    pub fn with_profile(profile: TargetProfile) -> Self {
        debug_assert_eq!(profile.target, Target::Cuda);
        CudaGenerator { profile }
    }

    // ── SSA value naming (mirrors msl helpers::vname) ──────────────────
    fn vname(&self, vid: Option<ValueId>, block: &Block) -> String {
        match vid {
            Some(v) => match block.names.get(&v) {
                Some(hint) => format!("v_{hint}"),
                None => format!("v{}", v.as_u32()),
            },
            None => "/*<no-value>*/".to_string(),
        }
    }

    // ── Flat index expression for Load/Store (Phase-1: single index) ───
    fn emit_idx(&self, indices: &[IndexExpr], block: &Block) -> Result<String> {
        match indices {
            [] => Ok(String::new()),
            [one] => Ok(self.idx_term(one, block)),
            // Multi-dim row-major flatten is a Phase-2 concern (needs the
            // shape-stride model the MSL path has). Smoke kernels are 1-D.
            _ => Err(Error::UnsupportedOp(
                "cuda Phase 1: multi-dimensional index (use 1-D elementwise)".into(),
            )),
        }
    }

    fn idx_term(&self, ix: &IndexExpr, block: &Block) -> String {
        match ix {
            IndexExpr::Value(v) => self.vname(Some(*v), block),
            IndexExpr::Const(c) => c.to_string(),
            IndexExpr::Range(v, off) => format!("({} + {off})", self.vname(Some(*v), block)),
        }
    }

    // ── Kernel signature ───────────────────────────────────────────────
    fn emit_signature(&self, kernel: &Kernel, out: &mut String) -> Result<()> {
        writeln!(out, "extern \"C\" __global__ void {}(", kernel.name).ok();
        let mut args: Vec<String> = Vec::new();
        for p in &kernel.params {
            args.push(self.emit_param(p)?);
        }
        for ce in &kernel.constexprs {
            // Scalars are passed by value as kernel arguments.
            args.push(format!("    {} {}", cuda_type_name(ce.dtype), ce.name.name()));
        }
        // Elementwise kernels carry a synthetic element-count for the bounds
        // guard. Reduction kernels are bounded per-row by the strided loop's
        // `end`, so they need no such param.
        if kernel.mode == KernelMode::Elementwise {
            args.push(format!("    unsigned int {N_ELEMS_PARAM}"));
        }
        writeln!(out, "{}", args.join(",\n")).ok();
        writeln!(out, ") {{").ok();
        Ok(())
    }

    fn emit_param(&self, p: &Param) -> Result<String> {
        match p.kind {
            ParamKind::Tensor => {
                let ty = cuda_type_name(p.dtype);
                Ok(if p.is_output {
                    format!("    {ty}* {}", p.name)
                } else {
                    format!("    const {ty}* {}", p.name)
                })
            }
            ParamKind::Scalar => Ok(format!("    {} {}", cuda_type_name(p.dtype), p.name)),
            ParamKind::Strided => Err(Error::UnsupportedOp(
                "cuda Phase 1: Strided params (Phase 2 — shape/stride buffers)".into(),
            )),
        }
    }

    // ── Body ───────────────────────────────────────────────────────────
    fn emit_body(&self, kernel: &Kernel, out: &mut String) -> Result<()> {
        match kernel.mode {
            KernelMode::Elementwise => {
                // Global linear thread id + bounds guard.
                writeln!(
                    out,
                    "    const unsigned int _gtid = blockIdx.x * blockDim.x + threadIdx.x;"
                )
                .ok();
                writeln!(out, "    if (_gtid >= {N_ELEMS_PARAM}) return;").ok();
                // `tid` alias: the DSL's `tid` lowers to Load{src:"tid"}; in
                // Elementwise mode it is the global linear index.
                writeln!(out, "    const unsigned int tid = _gtid;").ok();
            }
            KernelMode::Reduction => self.emit_reduction_preamble(out),
            KernelMode::Grid3D => {
                // 3-axis global thread id; ProgramId(axis) → gid_{x,y,z}.
                // Same launch geometry as Metal's dispatchThreadgroups, so
                // no extra bounds guard is needed (parity with Metal).
                writeln!(out, "    const unsigned int gid_x = blockIdx.x * blockDim.x + threadIdx.x;").ok();
                writeln!(out, "    const unsigned int gid_y = blockIdx.y * blockDim.y + threadIdx.y;").ok();
                writeln!(out, "    const unsigned int gid_z = blockIdx.z * blockDim.z + threadIdx.z;").ok();
            }
            other => {
                return Err(Error::UnsupportedOp(format!(
                    "cuda: KernelMode {other:?} unsupported (Elementwise/Reduction/Grid3D)"
                )));
            }
        }

        let block = &kernel.body;
        for (i, op) in block.ops.iter().enumerate() {
            let vid = block.results.get(i).and_then(|x| *x);
            self.emit_op(op, vid, block, kernel, out)?;
        }
        writeln!(out, "}}").ok();
        Ok(())
    }

    /// Reduction-mode preamble: maps Metal's threadgroup/simd built-ins to
    /// CUDA. Block-per-output-row; warp = 32-lane (the lucky match). The
    /// `n_simd == 0` guard mirrors the Metal freeze-hazard guard (harmless
    /// on CUDA, kept for parity).
    fn emit_reduction_preamble(&self, out: &mut String) {
        let lw = self.profile.lane_width;
        for line in [
            "    const unsigned int tid       = threadIdx.x;".to_string(),
            "    const unsigned int tgid_x    = blockIdx.x;".to_string(),
            "    const unsigned int tgid_y    = blockIdx.y;".to_string(),
            "    const unsigned int tgid_z    = blockIdx.z;".to_string(),
            "    const unsigned int lsize     = blockDim.x;".to_string(),
            format!("    const unsigned int n_simd    = lsize / {lw}u;"),
            "    if (n_simd == 0u) return;".to_string(),
            format!("    const unsigned int simd_lane  = threadIdx.x % {lw}u;"),
            format!("    const unsigned int simd_group = threadIdx.x / {lw}u;"),
        ] {
            writeln!(out, "{line}").ok();
        }
    }

    fn emit_op(
        &self,
        op: &Op,
        vid: Option<ValueId>,
        block: &Block,
        kernel: &Kernel,
        out: &mut String,
    ) -> Result<()> {
        let pad = "    ";
        match op {
            Op::ProgramId { axis } => {
                let v = self.vname(vid, block);
                let src = match kernel.mode {
                    // Elementwise: the single linear thread id.
                    KernelMode::Elementwise => "_gtid".to_string(),
                    // Reduction: which output row this block owns.
                    KernelMode::Reduction => {
                        match axis { 0 => "tgid_x", 1 => "tgid_y", _ => "tgid_z" }.to_string()
                    }
                    // Grid3D: per-axis global thread id.
                    _ => match axis { 0 => "gid_x", 1 => "gid_y", _ => "gid_z" }.to_string(),
                };
                writeln!(out, "{pad}unsigned int {v} = {src};").ok();
            }
            Op::Const { value } => {
                let v = self.vname(vid, block);
                if *value >= 0 {
                    writeln!(out, "{pad}unsigned int {v} = {value}u;").ok();
                } else {
                    writeln!(out, "{pad}int {v} = {value};").ok();
                }
            }
            Op::Load { src, indices, .. } => {
                let v = self.vname(vid, block);
                if indices.is_empty() {
                    writeln!(out, "{pad}auto {v} = {src};").ok();
                } else {
                    let idx = self.emit_idx(indices, block)?;
                    writeln!(out, "{pad}auto {v} = {src}[{idx}];").ok();
                }
            }
            Op::Store { dst, indices, value, .. } => {
                let val = self.vname(Some(*value), block);
                let idx = self.emit_idx(indices, block)?;
                writeln!(out, "{pad}{dst}[{idx}] = {val};").ok();
            }
            Op::BinOp { op: bop, lhs, rhs } => {
                let v = self.vname(vid, block);
                let l = self.vname(Some(*lhs), block);
                let r = self.vname(Some(*rhs), block);
                writeln!(out, "{pad}auto {v} = {};", cuda_binop(*bop, &l, &r)).ok();
            }
            Op::Fma { a, b, c } => {
                let v = self.vname(vid, block);
                let av = self.vname(Some(*a), block);
                let bv = self.vname(Some(*b), block);
                let cv = self.vname(Some(*c), block);
                writeln!(out, "{pad}auto {v} = fmaf({av}, {bv}, {cv});").ok();
            }
            Op::UnaryOp { op: uop, value } => {
                let v = self.vname(vid, block);
                let rv = self.vname(Some(*value), block);
                writeln!(out, "{pad}auto {v} = {};", self.cuda_unary(*uop, &rv)).ok();
            }
            Op::Cast { value, dtype } => {
                let v = self.vname(vid, block);
                let rv = self.vname(Some(*value), block);
                let ty = cuda_type_name(*dtype);
                // CUDA C-style cast; source type comes from `auto` inference.
                writeln!(out, "{pad}{ty} {v} = ({ty})({rv});").ok();
            }
            Op::Select { cond, on_true, on_false } => {
                let v = self.vname(vid, block);
                let c = self.vname(Some(*cond), block);
                let a = self.vname(Some(*on_true), block);
                let b = self.vname(Some(*on_false), block);
                writeln!(out, "{pad}auto {v} = ({c}) ? ({a}) : ({b});").ok();
            }
            Op::Activation { kind, value } => {
                let v = self.vname(vid, block);
                let rv = self.vname(Some(*value), block);
                let expr = match kind {
                    ActKind::Silu => format!("mt_silu((float)({rv}))"),
                    ActKind::Gelu => format!("mt_gelu((float)({rv}))"),
                    ActKind::Relu => format!("mt_relu((float)({rv}))"),
                    ActKind::Sigmoid => format!("mt_sigmoid((float)({rv}))"),
                    ActKind::Tanh => format!("tanhf((float)({rv}))"),
                };
                writeln!(out, "{pad}auto {v} = {expr};").ok();
            }
            // Single-warp SIMD reduction → xor butterfly so ALL lanes get
            // the result (matches Metal `simd_*` broadcast semantics).
            Op::SimdReduce { value, op: rk } => {
                let v = self.vname(vid, block);
                let rv = self.vname(Some(*value), block);
                let half = self.profile.lane_width / 2;
                writeln!(out, "{pad}float {v};").ok();
                writeln!(out, "{pad}{{").ok();
                writeln!(out, "{pad}    float _s = (float)({rv});").ok();
                writeln!(out, "{pad}    for (int _o = {half}; _o > 0; _o >>= 1) {{").ok();
                writeln!(out, "{pad}        float _x = __shfl_xor_sync(0xffffffffu, _s, _o);").ok();
                writeln!(out, "{pad}        _s = {};", reduce_combine(*rk, "_s", "_x")).ok();
                writeln!(out, "{pad}    }}").ok();
                if *rk == ReduceKind::Mean {
                    writeln!(out, "{pad}    {v} = _s / {}.0f;", self.profile.lane_width).ok();
                } else {
                    writeln!(out, "{pad}    {v} = _s;").ok();
                }
                writeln!(out, "{pad}}}").ok();
            }
            // Scalar (rank-0) splat / zeros. Tile (array) shapes need the
            // threadgroup/stack allocation path (cooperative kernels, P3+).
            Op::Zeros { shape, .. } if shape.rank() == 0 => {
                let v = self.vname(vid, block);
                writeln!(out, "{pad}float {v} = 0.0f;").ok();
            }
            Op::Splat { value, shape, .. } if shape.rank() == 0 => {
                let v = self.vname(vid, block);
                writeln!(out, "{pad}float {v} = {value}f;").ok();
            }
            // Per-thread grid-stride accumulation over a row (Phase 2).
            // Each thread sums src[offset+tid], src[offset+tid+lsize], …
            // Correctness-first: the 4-wide vectorized form the MSL path uses
            // is a Phase-3 perf retune (SCOPE §6).
            Op::StrideReduce {
                src, offset, end, op: rk, transform, secondary_src, ..
            } => {
                if transform.as_ref().is_some_and(|t| !t.is_empty()) || secondary_src.is_some() {
                    return Err(Error::UnsupportedOp(
                        "cuda Phase 2: StrideReduce transform/secondary_src (rms/gemv → Phase 3)"
                            .into(),
                    ));
                }
                let v = self.vname(vid, block);
                let off = self.vname(Some(*offset), block);
                let en = self.vname(Some(*end), block);
                writeln!(out, "{pad}float {v} = {};", reduce_init(*rk)).ok();
                writeln!(
                    out,
                    "{pad}for (unsigned int _i = {off} + tid; _i < {en}; _i += lsize) {{"
                )
                .ok();
                writeln!(out, "{pad}    float _e = (float)({src}[_i]);").ok();
                writeln!(out, "{pad}    {v} = {};", reduce_combine(*rk, &v, "_e")).ok();
                writeln!(out, "{pad}}}").ok();
            }
            // Threadgroup-scope reduction: warp shuffle + shared-mem tree
            // (the CUDA analog of msl::reduce two-level simd_sum). Phase 2.
            Op::Reduce { value, axis, op: rk } => {
                if *axis != 0 {
                    return Err(Error::UnsupportedOp(
                        "cuda Phase 2: Reduce axis != 0 (Phase 3)".into(),
                    ));
                }
                let v = self.vname(vid, block);
                let input = self.vname(Some(*value), block);
                self.emit_reduce_tree(&v, &input, *rk, out);
            }
            other => {
                return Err(Error::UnsupportedOp(format!(
                    "cuda: op {} not supported yet",
                    op_variant_name(other)
                )));
            }
        }
        Ok(())
    }

    /// Two-level threadgroup reduction: warp shuffle (`__shfl_down_sync`)
    /// then a `__shared__` tree across warps — the CUDA analog of
    /// `msl::reduce`'s `simd_sum` + threadgroup-memory path. Lane width 32
    /// matches Metal's simdgroup (the lucky structural match). Assumes
    /// `blockDim.x` is a multiple of 32 (Phase-2 constraint; partial-warp
    /// masking is a Phase-3 refinement).
    fn emit_reduce_tree(&self, result: &str, input: &str, kind: ReduceKind, out: &mut String) {
        let pad = "    ";
        let lw = self.profile.lane_width;
        let half = lw / 2;
        let init = reduce_init(kind);
        let buf = format!("{result}_sg");
        writeln!(out, "{pad}__shared__ float {buf}[32];").ok();
        writeln!(out, "{pad}float {result};").ok();
        writeln!(out, "{pad}{{").ok();
        // Phase 1: intra-warp reduction.
        writeln!(out, "{pad}    float _sv = (float)({input});").ok();
        writeln!(out, "{pad}    for (int _o = {half}; _o > 0; _o >>= 1) {{").ok();
        writeln!(out, "{pad}        float _ov = __shfl_down_sync(0xffffffffu, _sv, _o);").ok();
        writeln!(out, "{pad}        _sv = {};", reduce_combine(kind, "_sv", "_ov")).ok();
        writeln!(out, "{pad}    }}").ok();
        // Phase 2: lane 0 of each warp publishes its total.
        writeln!(out, "{pad}    if (simd_lane == 0u) {buf}[simd_group] = _sv;").ok();
        writeln!(out, "{pad}    __syncthreads();").ok();
        // Phase 3: warp 0 reduces the per-warp totals and broadcasts via [0].
        writeln!(out, "{pad}    if (simd_group == 0u) {{").ok();
        writeln!(out, "{pad}        float _wv = simd_lane < n_simd ? {buf}[simd_lane] : {init};").ok();
        writeln!(out, "{pad}        for (int _o = {half}; _o > 0; _o >>= 1) {{").ok();
        writeln!(out, "{pad}            float _ov = __shfl_down_sync(0xffffffffu, _wv, _o);").ok();
        writeln!(out, "{pad}            _wv = {};", reduce_combine(kind, "_wv", "_ov")).ok();
        writeln!(out, "{pad}        }}").ok();
        writeln!(out, "{pad}        if (simd_lane == 0u) {buf}[0] = _wv;").ok();
        writeln!(out, "{pad}    }}").ok();
        writeln!(out, "{pad}    __syncthreads();").ok();
        if kind == ReduceKind::Mean {
            writeln!(out, "{pad}    {result} = {buf}[0] / (float)lsize;").ok();
        } else {
            writeln!(out, "{pad}    {result} = {buf}[0];").ok();
        }
        writeln!(out, "{pad}}}").ok();
    }

    fn cuda_unary(&self, op: UnaryOpKind, arg: &str) -> String {
        use UnaryOpKind::*;
        match op {
            Neg => format!("(-{arg})"),
            Recip => format!("(1.0f / {arg})"),
            // sign(x): -1/0/+1 (matches Metal `sign`, incl. 0 → 0).
            // `copysignf` would map 0 → +1, so emit the explicit form.
            Sign => format!("((float)({arg}) > 0.0f ? 1.0f : ((float)({arg}) < 0.0f ? -1.0f : 0.0f))"),
            // Block-scaled-quant decode helpers (preamble __device__ fns).
            DecodeE2m1 => format!("mt_decode_e2m1((unsigned int)({arg}))"),
            DecodeE4m3 => format!("mt_decode_e4m3((unsigned int)({arg}))"),
            DecodeE5m2 => format!("mt_decode_e5m2((unsigned int)({arg}))"),
            DecodeInt8 => format!("mt_decode_int8((unsigned int)({arg}))"),
            _ => format!("{}({arg})", self.profile.unary_intrinsic(op)),
        }
    }
}

impl CodegenBackend for CudaGenerator {
    fn target(&self) -> Target { Target::Cuda }

    fn profile(&self) -> &TargetProfile { &self.profile }

    fn generate(&self, kernel: &Kernel) -> Result<String> {
        let mut out = String::new();
        out.push_str(CUDA_PREAMBLE);
        self.emit_signature(kernel, &mut out)?;
        self.emit_body(kernel, &mut out)?;
        Ok(out)
    }
}

/// DType → CUDA C++ scalar type name.
pub fn cuda_type_name(dt: DType) -> &'static str {
    match dt {
        DType::F32 => "float",
        DType::F16 => "__half",
        DType::BF16 => "__nv_bfloat16",
        DType::I32 => "int",
        DType::U32 => "unsigned int",
        DType::I8 => "signed char",
        DType::U8 => "unsigned char",
        DType::I4 => "signed char", // packed; sub-byte handled in decode helpers
        DType::U16 => "unsigned short",
        DType::I64 => "long long",
        DType::U64 => "unsigned long long",
        DType::Bool => "bool",
    }
}

/// BinOp → CUDA expression (infix for arithmetic/compare/bitwise,
/// function-call for the few that need it). Mirrors `BinOpKind::msl_symbol`
/// semantics with CUDA intrinsic names.
fn cuda_binop(op: BinOpKind, l: &str, r: &str) -> String {
    use BinOpKind::*;
    match op {
        Add => format!("{l} + {r}"),
        Sub => format!("{l} - {r}"),
        Mul => format!("{l} * {r}"),
        Div => format!("{l} / {r}"),
        // fmaxf/fminf with float casts: plain `max`/`min` is ambiguous on
        // `auto`-typed operands and missing for __half/__nv_bfloat16.
        Max => format!("fmaxf((float)({l}), (float)({r}))"),
        Min => format!("fminf((float)({l}), (float)({r}))"),
        Pow => format!("powf({l}, {r})"),
        ATan2 => format!("atan2f({l}, {r})"),
        Rem => format!("fmodf({l}, {r})"),
        Mod => format!("({l} % {r})"),
        And => format!("({l} && {r})"),
        Or => format!("({l} || {r})"),
        Xor => format!("((bool){l} != (bool){r})"),
        BitAnd => format!("({l} & {r})"),
        BitOr => format!("({l} | {r})"),
        BitXor => format!("({l} ^ {r})"),
        Shl => format!("({l} << {r})"),
        Shr => format!("({l} >> {r})"),
        CmpLt => format!("({l} < {r})"),
        CmpGt => format!("({l} > {r})"),
        CmpLe => format!("({l} <= {r})"),
        CmpGe => format!("({l} >= {r})"),
        CmpEq => format!("({l} == {r})"),
        CmpNe => format!("({l} != {r})"),
    }
}

/// Identity / initial accumulator value for a reduction kind.
fn reduce_init(kind: ReduceKind) -> &'static str {
    match kind {
        ReduceKind::Sum | ReduceKind::Mean => "0.0f",
        ReduceKind::Max => "(-MT_INF)",
        ReduceKind::Min => "MT_INF",
        ReduceKind::Product => "1.0f",
    }
}

/// Binary combine for a reduction kind: `combine(a, b)` as a CUDA expr.
fn reduce_combine(kind: ReduceKind, a: &str, b: &str) -> String {
    match kind {
        ReduceKind::Sum | ReduceKind::Mean => format!("{a} + {b}"),
        ReduceKind::Max => format!("fmaxf({a}, {b})"),
        ReduceKind::Min => format!("fminf({a}, {b})"),
        ReduceKind::Product => format!("{a} * {b}"),
    }
}

/// Variant name of an `Op` (Debug-derived), for diagnostics.
fn op_variant_name(op: &Op) -> String {
    let dbg = format!("{op:?}");
    dbg.split([' ', '{', '(']).next().unwrap_or("?").to_string()
}

#[cfg(test)]
mod tests {
    use metaltile_core::ir::{BinOpKind, IndexExpr, Op};
    use metaltile_core::shape::Shape;

    use super::*;

    fn vector_add_ir() -> Kernel {
        // Mirrors the codegen MSL test's `vector_add`: out[i] = a[i] + b[i].
        let mut k = Kernel::new("vector_add");
        for (name, is_out) in [("a", false), ("b", false), ("c", true)] {
            k.params.push(Param {
                name: name.into(),
                dtype: DType::F32,
                shape: Shape::scalar(),
                is_output: is_out,
                kind: ParamKind::Tensor,
            });
        }
        k.body.push_op(Op::ProgramId { axis: 0 }, ValueId::new(0));
        k.body.name_value(ValueId::new(0), "idx");
        k.body.push_op(
            Op::Load { src: "a".into(), indices: vec![IndexExpr::Value(ValueId::new(0))], mask: None, other: None },
            ValueId::new(1),
        );
        k.body.name_value(ValueId::new(1), "x");
        k.body.push_op(
            Op::Load { src: "b".into(), indices: vec![IndexExpr::Value(ValueId::new(0))], mask: None, other: None },
            ValueId::new(2),
        );
        k.body.name_value(ValueId::new(2), "y");
        k.body.push_op(
            Op::BinOp { op: BinOpKind::Add, lhs: ValueId::new(1), rhs: ValueId::new(2) },
            ValueId::new(3),
        );
        k.body.name_value(ValueId::new(3), "sum");
        k.body.push_op_no_result(Op::Store {
            dst: "c".into(),
            indices: vec![IndexExpr::Value(ValueId::new(0))],
            value: ValueId::new(3),
            mask: None,
        });
        k
    }

    #[test]
    fn emits_vector_add_cuda() {
        let g = CudaGenerator::new();
        let src = g.generate(&vector_add_ir()).unwrap();
        // Signature: pointers + synthetic bounds param.
        assert!(src.contains("extern \"C\" __global__ void vector_add("));
        assert!(src.contains("const float* a"));
        assert!(src.contains("const float* b"));
        assert!(src.contains("float* c"));
        assert!(src.contains(&format!("unsigned int {N_ELEMS_PARAM}")));
        // Body: global tid + guard + the add.
        assert!(src.contains("blockIdx.x * blockDim.x + threadIdx.x"));
        assert!(src.contains(&format!("if (_gtid >= {N_ELEMS_PARAM}) return;")));
        assert!(src.contains("unsigned int v_idx = _gtid;"));
        assert!(src.contains("auto v_x = a[v_idx];"));
        assert!(src.contains("auto v_y = b[v_idx];"));
        assert!(src.contains("auto v_sum = v_x + v_y;"));
        assert!(src.contains("c[v_idx] = v_sum;"));
    }

    fn row_reduce_ir() -> Kernel {
        // out[row] = sum(inp[row*n .. row*n+n]) — Reduction mode.
        let mut k = Kernel::new("row_reduce_sum");
        k.mode = KernelMode::Reduction;
        k.params.push(Param {
            name: "inp".into(), dtype: DType::F32, shape: Shape::scalar(),
            is_output: false, kind: ParamKind::Tensor,
        });
        k.params.push(Param {
            name: "out".into(), dtype: DType::F32, shape: Shape::scalar(),
            is_output: true, kind: ParamKind::Tensor,
        });
        k.constexprs.push(metaltile_core::ir::ConstExprDecl {
            name: metaltile_core::constexpr::ConstExpr::new("n"),
            dtype: DType::U32,
            value: None,
        });
        let (row, nv, rs, re, acc, res) = (
            ValueId::new(0), ValueId::new(1), ValueId::new(2),
            ValueId::new(3), ValueId::new(4), ValueId::new(5),
        );
        k.body.push_op(Op::ProgramId { axis: 0 }, row);
        k.body.name_value(row, "row");
        k.body.push_op(Op::Load { src: "n".into(), indices: vec![], mask: None, other: None }, nv);
        k.body.push_op(Op::BinOp { op: BinOpKind::Mul, lhs: row, rhs: nv }, rs);
        k.body.name_value(rs, "rs");
        k.body.push_op(Op::BinOp { op: BinOpKind::Add, lhs: rs, rhs: nv }, re);
        k.body.name_value(re, "re");
        k.body.push_op(
            Op::StrideReduce {
                src: "inp".into(), offset: rs, stride: nv, end: re,
                op: ReduceKind::Sum, dtype: DType::F32,
                transform: None, secondary_src: None, secondary_base: None,
            },
            acc,
        );
        k.body.name_value(acc, "acc");
        k.body.push_op(Op::Reduce { value: acc, axis: 0, op: ReduceKind::Sum }, res);
        k.body.name_value(res, "result");
        k.body.push_op_no_result(Op::Store {
            dst: "out".into(), indices: vec![IndexExpr::Value(row)], value: res, mask: None,
        });
        k
    }

    #[test]
    fn emits_row_reduce_cuda() {
        let src = CudaGenerator::new().generate(&row_reduce_ir()).unwrap();
        // Reduction signature: no synthetic _n_elems param.
        assert!(src.contains("extern \"C\" __global__ void row_reduce_sum("));
        assert!(src.contains("unsigned int n"));
        assert!(!src.contains(N_ELEMS_PARAM));
        // Reduction preamble (block-per-row, warp = 32 lanes).
        assert!(src.contains("const unsigned int tgid_x    = blockIdx.x;"));
        assert!(src.contains("const unsigned int n_simd    = lsize / 32u;"));
        assert!(src.contains("const unsigned int simd_lane  = threadIdx.x % 32u;"));
        // Per-thread grid-stride accumulation.
        assert!(src.contains("for (unsigned int _i = v_rs + tid; _i < v_re; _i += lsize)"));
        // Two-level tree: warp shuffle + shared mem + barriers.
        assert!(src.contains("__shfl_down_sync(0xffffffffu"));
        assert!(src.contains("__shared__ float v_result_sg[32];"));
        assert!(src.contains("__syncthreads();"));
        assert!(src.contains("out[v_row] = v_result;"));
    }

    #[test]
    fn rejects_unsupported_mode() {
        let mut k = vector_add_ir();
        k.mode = KernelMode::Tile2D;
        assert!(CudaGenerator::new().generate(&k).is_err());
    }

    #[test]
    fn cuda_generator_reports_cuda_target_and_profile() {
        let g = CudaGenerator::new();
        assert_eq!(g.target(), Target::Cuda);
        assert_eq!(g.profile().shared_mem_kw, "__shared__");
        assert_eq!(g.profile().lane_width, 32);
    }
}
