//! MSL (Metal Shading Language) code generator.
//!
//! Walks the MetalTile IR and emits valid MSL source text.
//! Handles constexpr params, tiled matmul, vectorized loads, and thread indexing.

pub(crate) mod features;
pub(crate) mod matmul;
pub(crate) mod preamble;
pub(crate) mod reduce;

use std::{collections::BTreeMap, fmt::Write};

use features::KernelFeatures;
use matmul::{dim_to_msl_str, fmt_float};
use metaltile_core::{
    dtype::DType,
    ir::{
        BinOpKind,
        Block,
        BlockId,
        IndexExpr,
        Kernel,
        KernelMode,
        Op,
        ParamKind,
        ReduceKind,
        ValueId,
    },
    shape::Shape,
};

use crate::{
    error::Result,
    passes,
    passes::{
        tile_lowering::TileSchedule,
        type_check::{TypeEnv, infer_types},
    },
};

#[macro_export]
macro_rules! wl {
    ($out:expr) => {{ let _ = writeln!($out); }};
    ($out:expr, $($arg:tt)*) => {{ let _ = writeln!($out, $($arg)*); }};
}

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

#[derive(Debug, Clone)]
pub struct MslConfig {
    pub simd_size: u32,
    /// Emit `simdgroup_multiply_accumulate` (requires Metal GPU family 7+ / M1+).
    /// On Apple9 (M3+) this uses dedicated matrix hardware; on Apple7/8 (M1/M2)
    /// it is emulated via FMA on the simdgroup.
    pub use_simd_matrix: bool,
    pub debug_comments: bool,
    /// Use native `bfloat` type (Metal 3.1+, M3+). When false, uses `bfloat16_t` struct.
    pub native_bfloat: bool,
    /// Emit `async_copy` prefetch (requires Metal 3 / M2+).
    pub async_copy: bool,
    pub tile_schedule: TileSchedule,
}

impl Default for MslConfig {
    fn default() -> Self {
        MslConfig {
            simd_size: 32,
            use_simd_matrix: false,
            debug_comments: false,
            native_bfloat: true,
            async_copy: false,
            tile_schedule: TileSchedule::default(),
        }
    }
}

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------

pub struct MslGenerator {
    config: MslConfig,
}

impl MslGenerator {
    pub fn new(config: MslConfig) -> Self { MslGenerator { config } }

    pub fn generate(&self, kernel: &Kernel) -> Result<String> {
        // Run the optimization pipeline on a clone before emitting.
        let mut k = kernel.clone();
        passes::run_passes(&mut k, &passes::standard_pipeline())?;

        let type_env = infer_types(&k)?;
        let feat = self.analyze(&k);
        let mut out = String::new();
        wl!(out, "// Generated by MetalTile");
        wl!(out, "#include <metal_stdlib>");
        wl!(out, "using namespace metal;");
        if feat.needs_bf16_struct && !self.config.native_bfloat {
            self.emit_bf16_preamble(&mut out);
        }
        if self.config.use_simd_matrix {
            wl!(out);
            wl!(out, "#include <metal_simdgroup_matrix>");
        }
        self.emit_activation_helpers(&feat, &mut out);
        wl!(out);
        self.emit_kernel(&k, &feat, &type_env, &mut out)?;
        Ok(out)
    }

    // ---- type helpers ----------------------------------------------------

    pub(crate) fn msl_type_name(&self, dtype: DType) -> &'static str {
        if dtype == DType::BF16 && !self.config.native_bfloat {
            "bfloat16_t"
        } else {
            dtype.msl_name()
        }
    }

    pub(crate) fn emit_cast_expr(&self, dtype: DType, value: &str) -> String {
        if dtype == DType::BF16 {
            format!("{}({value})", self.msl_type_name(dtype))
        } else {
            format!("static_cast<{}>({value})", self.msl_type_name(dtype))
        }
    }

    // ---- kernel signature ------------------------------------------------

    fn emit_kernel(
        &self,
        kernel: &Kernel,
        feat: &KernelFeatures,
        type_env: &TypeEnv,
        out: &mut String,
    ) -> Result<()> {
        let mut buf_idx = 0u32;

        write!(out, "kernel void {}(", kernel.name).unwrap();

        // Tensor/Strided/Scalar params.
        for p in &kernel.params {
            match p.kind {
                ParamKind::Tensor => {
                    let q = if p.is_output { "device " } else { "const device " };
                    write!(
                        out,
                        "\n    {q}{} *{} [[buffer({buf_idx})]],",
                        self.msl_type_name(p.dtype),
                        p.name
                    )
                    .unwrap();
                    buf_idx += 1;
                },
                ParamKind::Strided => {
                    let q = if p.is_output { "device " } else { "const device " };
                    write!(
                        out,
                        "\n    {q}{} *{} [[buffer({buf_idx})]],",
                        self.msl_type_name(p.dtype),
                        p.name
                    )
                    .unwrap();
                    buf_idx += 1;
                    write!(out, "\n    constant uint *{}_shape [[buffer({buf_idx})]],", p.name)
                        .unwrap();
                    buf_idx += 1;
                    write!(out, "\n    constant uint *{}_strides [[buffer({buf_idx})]],", p.name)
                        .unwrap();
                    buf_idx += 1;
                },
                ParamKind::Scalar => {
                    write!(
                        out,
                        "\n    constant {} &{} [[buffer({buf_idx})]],",
                        self.msl_type_name(p.dtype),
                        p.name
                    )
                    .unwrap();
                    buf_idx += 1;
                },
            }
        }

        // Constexpr params.
        for ce in &kernel.constexprs {
            let msl_type = match ce.dtype {
                DType::F32 => "float",
                DType::F16 => "half",
                DType::BF16 => "float",
                DType::I32 => "int",
                DType::I64 => "long",
                DType::U64 => "ulong",
                _ => "uint",
            };
            write!(out, "\n    constant {msl_type} &{} [[buffer({buf_idx})]],", ce.name.name())
                .unwrap();
            buf_idx += 1;
        }

        // Thread / threadgroup position attributes.
        match kernel.mode {
            KernelMode::Elementwise => {
                write!(out, "\n    uint tid [[thread_position_in_grid]]").unwrap();
            },
            KernelMode::Reduction => {
                write!(out, "\n    uint3 _tid3  [[thread_position_in_threadgroup]],").unwrap();
                write!(out, "\n    uint3 _tgid3 [[threadgroup_position_in_grid]],").unwrap();
                write!(out, "\n    uint3 _lsize3 [[threads_per_threadgroup]]").unwrap();
            },
            KernelMode::Grid3D => {
                write!(out, "\n    uint3 gid [[thread_position_in_grid]]").unwrap();
            },
            KernelMode::Tile2D => {
                write!(out, "\n    uint2 tid  [[thread_position_in_threadgroup]],").unwrap();
                write!(out, "\n    uint2 tgid [[threadgroup_position_in_grid]]").unwrap();
            },
        }
        if feat.needs_simd_lane {
            write!(out, ",\n    uint simd_lane [[thread_index_in_simdgroup]]").unwrap();
        }
        if feat.needs_simd_group && !feat.is_matmul {
            write!(out, ",\n    uint simd_id [[simdgroup_index_in_threadgroup]]").unwrap();
        }
        if self.config.use_simd_matrix && feat.is_matmul {
            write!(out, ",\n    uint simd_group [[simdgroup_index_in_threadgroup]]").unwrap();
            write!(out, ",\n    uint simd_lane [[thread_index_in_simdgroup]]").unwrap();
        }

        wl!(out, "\n) {{");

        // Inject scalar aliases for Reduction mode.
        if kernel.mode == KernelMode::Reduction {
            wl!(out, "    uint tid    = _tid3.x;");
            wl!(out, "    uint tgid_x = _tgid3.x;");
            wl!(out, "    uint tgid_y = _tgid3.y;");
            wl!(out, "    uint lsize  = _lsize3.x;");
            if feat.needs_simd_group {
                wl!(out, "    uint n_simd = lsize / 32u;");
            }
        }

        // Two-pass: collect threadgroup hoists first, then emit body.
        let mut body_buf = String::new();
        let mut hoists: Vec<String> = Vec::new();
        let extra_names: BTreeMap<ValueId, String> = BTreeMap::new();

        if feat.is_matmul {
            self.emit_tiled(&mut body_buf, "    ", kernel, None)?;
        } else {
            self.emit_block(
                &kernel.body,
                &kernel.blocks,
                &mut body_buf,
                1,
                kernel,
                type_env,
                &extra_names,
                &mut hoists,
            )?;
        }

        for h in &hoists {
            wl!(out, "    {h}");
        }
        if !hoists.is_empty() {
            wl!(out);
        }
        out.push_str(&body_buf);

        wl!(out, "}}");
        Ok(())
    }

    // ---- block emission --------------------------------------------------

    #[allow(clippy::too_many_arguments)]
    fn emit_block(
        &self,
        block: &Block,
        all_blocks: &BTreeMap<BlockId, Block>,
        out: &mut String,
        indent: usize,
        kernel: &Kernel,
        type_env: &TypeEnv,
        extra_names: &BTreeMap<ValueId, String>,
        hoists: &mut Vec<String>,
    ) -> Result<()> {
        let has_tile = matches!(kernel.mode, KernelMode::Tile2D);
        let pad = "    ".repeat(indent);

        // Deduplicate variable names within this block.
        let mut dedup_extra = extra_names.clone();
        {
            use std::collections::BTreeMap as Map;
            let mut name_counts: Map<String, u32> = Map::new();
            for (vid, raw_name) in &block.names {
                let base = format!("v_{raw_name}");
                let count = name_counts.entry(base.clone()).or_insert(0);
                *count += 1;
                if *count > 1 {
                    dedup_extra.insert(*vid, format!("{base}_{count}"));
                }
            }
        }
        let extra_names = &dedup_extra;

        for (i, op) in block.ops.iter().enumerate() {
            let vid = block.results.get(i).and_then(|x| *x);

            match op {
                // ---- indexing ------------------------------------------
                Op::ProgramId { axis } => {
                    let v = self.vname(vid, block, extra_names);
                    match kernel.mode {
                        KernelMode::Elementwise => match axis {
                            0 => wl!(out, "{pad}uint {v} = tid;"),
                            _ => wl!(out, "{pad}uint {v} = 0;"),
                        },
                        KernelMode::Reduction => match axis {
                            0 => wl!(out, "{pad}uint {v} = tgid_x;"),
                            1 => wl!(out, "{pad}uint {v} = tgid_y;"),
                            _ => wl!(out, "{pad}uint {v} = 0;"),
                        },
                        KernelMode::Grid3D => match axis {
                            0 => wl!(out, "{pad}uint {v} = gid.x;"),
                            1 => wl!(out, "{pad}uint {v} = gid.y;"),
                            2 => wl!(out, "{pad}uint {v} = gid.z;"),
                            _ => wl!(out, "{pad}uint {v} = 0;"),
                        },
                        KernelMode::Tile2D => match axis {
                            0 => wl!(out, "{pad}uint {v} = tgid.x;"),
                            1 => wl!(out, "{pad}uint {v} = tgid.y;"),
                            _ => wl!(out, "{pad}uint {v} = 0;"),
                        },
                    }
                },

                Op::Const { value } => {
                    let v = self.vname(vid, block, extra_names);
                    wl!(out, "{pad}int {v} = {value};");
                },

                Op::Arange { start, step, len } => {
                    let v = self.vname(vid, block, extra_names);
                    let s0 = start.unwrap_or(0.0);
                    let ds = step.unwrap_or(1.0);
                    let raw_idx = if has_tile {
                        format!("(tid.y * {len} + tid.x) % {len}")
                    } else if kernel.mode == KernelMode::Grid3D {
                        format!("gid.x % {len}")
                    } else {
                        format!("tid % {len}")
                    };
                    if s0 == 0.0 && ds == 1.0 {
                        wl!(out, "{pad}uint {v} = {raw_idx};");
                    } else {
                        wl!(out, "{pad}float {v} = {s0}f + float({raw_idx}) * {ds}f;");
                    }
                },

                // ---- memory --------------------------------------------
                Op::Load { src, indices, .. } => {
                    let v = self.vname(vid, block, extra_names);
                    let src_dtype = kernel.params.iter().find(|p| p.name == *src).map(|p| p.dtype);
                    let promote_bf16 = self.config.native_bfloat
                        && src_dtype == Some(DType::BF16)
                        && kernel.mode == KernelMode::Elementwise;
                    if indices.is_empty() {
                        if promote_bf16 {
                            wl!(out, "{pad}float {v} = float({src});");
                        } else {
                            wl!(out, "{pad}auto {v} = {src};");
                        }
                    } else {
                        let idx = self.emit_idx(indices, block, extra_names, kernel, src);
                        if promote_bf16 {
                            wl!(out, "{pad}float {v} = float({src}[{idx}]);");
                        } else {
                            wl!(out, "{pad}auto {v} = {src}[{idx}];");
                        }
                    }
                },

                Op::Store { dst, indices, value, .. } => {
                    let idx = self.emit_idx(indices, block, extra_names, kernel, dst);
                    let val = self.vname(Some(*value), block, extra_names);
                    let dst_dtype = kernel.params.iter().find(|p| p.name == *dst).map(|p| p.dtype);
                    if self.config.native_bfloat && dst_dtype == Some(DType::BF16) {
                        wl!(out, "{pad}{dst}[{idx}] = bfloat({val});");
                    } else {
                        wl!(out, "{pad}{dst}[{idx}] = {val};");
                    }
                },

                Op::Zeros { dtype, shape } => {
                    let v = self.vname(vid, block, extra_names);
                    let (decl, init_lines) = self.emit_tile_alloc(dtype, shape, &v, 0.0);
                    wl!(out, "{pad}{decl};");
                    for line in &init_lines {
                        wl!(out, "{pad}{line}");
                    }
                },

                Op::Splat { value: sv, dtype, shape } => {
                    let v = self.vname(vid, block, extra_names);
                    let (decl, _) = self.emit_tile_alloc(dtype, shape, &v, *sv);
                    let lit = fmt_float(*sv, dtype);
                    wl!(out, "{pad}{decl};");
                    match shape.num_elements() {
                        Some(1) | None if shape.rank() == 0 => {
                            wl!(out, "{pad}{v} = {lit};");
                        },
                        _ => {
                            let n = self.shape_nelems_str(shape);
                            wl!(out, "{pad}for (uint _i = 0; _i < {n}; _i++) {v}[_i] = {lit};");
                        },
                    }
                },

                Op::Slice { value, ranges } => {
                    let v = self.vname(vid, block, extra_names);
                    let rv = self.vname(Some(*value), block, extra_names);
                    let offset_str = type_env
                        .get(value)
                        .and_then(|tv| {
                            let shape = &tv.shape;
                            let rank = shape.rank();
                            if rank <= 1 {
                                None
                            } else {
                                let mut parts: Vec<String> = Vec::new();
                                for &(axis, start, _len) in ranges {
                                    if start == 0 {
                                        continue;
                                    }
                                    let stride_dims: Vec<String> = (axis as usize + 1..rank)
                                        .filter_map(|i| shape.dim(i))
                                        .map(dim_to_msl_str)
                                        .collect();
                                    if stride_dims.is_empty() {
                                        parts.push(start.to_string());
                                    } else {
                                        parts.push(format!(
                                            "{} * {}",
                                            start,
                                            stride_dims.join(" * ")
                                        ));
                                    }
                                }
                                if parts.is_empty() { None } else { Some(parts.join(" + ")) }
                            }
                        })
                        .unwrap_or_else(|| {
                            ranges.iter().map(|(_, start, _)| start).sum::<i64>().to_string()
                        });
                    if offset_str == "0" {
                        wl!(out, "{pad}auto {v} = {rv};");
                    } else {
                        wl!(out, "{pad}auto {v} = {rv} + {offset_str};");
                    }
                },

                Op::Transpose { value } => {
                    let v = self.vname(vid, block, extra_names);
                    let rv = self.vname(Some(*value), block, extra_names);
                    if let Some(tv) = type_env.get(value) {
                        let rank = tv.shape.rank();
                        if rank == 2 {
                            let m = tv.shape.dim(0).map(dim_to_msl_str).unwrap_or("M".into());
                            let n = tv.shape.dim(1).map(dim_to_msl_str).unwrap_or("N".into());
                            let t = self.msl_type_name(tv.dtype);
                            wl!(out, "{pad}{t} {v}[{m} * {n}];");
                            wl!(out, "{pad}for (uint r = 0; r < {m}; r++) {{");
                            wl!(out, "{pad}    for (uint c = 0; c < {n}; c++) {{");
                            wl!(out, "{pad}        {v}[c * {m} + r] = {rv}[r * {n} + c];");
                            wl!(out, "{pad}    }}");
                            wl!(out, "{pad}}}");
                        } else {
                            wl!(out, "{pad}// Transpose: unsupported rank {rank}");
                            wl!(out, "{pad}auto {v} = {rv};");
                        }
                    } else {
                        wl!(out, "{pad}// Transpose: caller uses transposed index strides");
                        wl!(out, "{pad}auto {v} = {rv};");
                    }
                },

                // ---- compute -------------------------------------------
                Op::BinOp { op, lhs, rhs } => {
                    let v = self.vname(vid, block, extra_names);
                    let l = self.vname(Some(*lhs), block, extra_names);
                    let r = self.vname(Some(*rhs), block, extra_names);
                    match op {
                        BinOpKind::Max | BinOpKind::Min | BinOpKind::Pow => {
                            wl!(out, "{pad}auto {v} = {}({l}, {r});", op.msl_symbol())
                        },
                        BinOpKind::And => wl!(out, "{pad}auto {v} = ({l} && {r});"),
                        BinOpKind::Or => wl!(out, "{pad}auto {v} = ({l} || {r});"),
                        BinOpKind::Xor => wl!(out, "{pad}auto {v} = ((bool){l} != (bool){r});"),
                        BinOpKind::BitAnd => wl!(out, "{pad}auto {v} = ({l} & {r});"),
                        BinOpKind::BitOr => wl!(out, "{pad}auto {v} = ({l} | {r});"),
                        BinOpKind::BitXor => wl!(out, "{pad}auto {v} = ({l} ^ {r});"),
                        BinOpKind::Shl => wl!(out, "{pad}auto {v} = ({l} << {r});"),
                        BinOpKind::Shr => wl!(out, "{pad}auto {v} = ({l} >> {r});"),
                        _ => wl!(out, "{pad}auto {v} = {l} {} {r};", op.msl_symbol()),
                    }
                },

                Op::UnaryOp { op, value } => {
                    let v = self.vname(vid, block, extra_names);
                    let rv = self.vname(Some(*value), block, extra_names);
                    let expr = op.msl_emit(&rv);
                    wl!(out, "{pad}auto {v} = {expr};");
                },

                Op::Activation { kind, value } => {
                    let v = self.vname(vid, block, extra_names);
                    let rv = self.vname(Some(*value), block, extra_names);
                    wl!(out, "{pad}auto {v} = {}({rv});", kind.msl_fn());
                },

                Op::Select { cond, on_true, on_false } => {
                    let v = self.vname(vid, block, extra_names);
                    let vc = self.vname(Some(*cond), block, extra_names);
                    let vt = self.vname(Some(*on_true), block, extra_names);
                    let vf = self.vname(Some(*on_false), block, extra_names);
                    wl!(out, "{pad}auto {v} = select({vf}, {vt}, bool({vc}));");
                },

                Op::Broadcast { value, shape } => {
                    let v = self.vname(vid, block, extra_names);
                    let rv = self.vname(Some(*value), block, extra_names);
                    let n = self.shape_nelems_str(shape);
                    let dt = type_env
                        .get(value)
                        .map(|tv| self.msl_type_name(tv.dtype))
                        .unwrap_or("float");
                    wl!(out, "{pad}{dt} {v}_data[{n}];");
                    wl!(out, "{pad}for (uint _i = 0; _i < {n}; _i++) {v}_data[_i] = {dt}({rv});");
                    wl!(out, "{pad}{dt}* {v} = {v}_data;");
                },

                Op::Dot { .. } => {
                    self.emit_tiled(out, &pad, kernel, vid)?;
                },

                Op::StrideReduce {
                    src,
                    offset,
                    stride,
                    end,
                    op: rk,
                    transform,
                    secondary_src,
                    secondary_base,
                    ..
                } => {
                    let v = self.vname(vid, block, extra_names);
                    let off = self.vname(Some(*offset), block, extra_names);
                    let st = self.vname(Some(*stride), block, extra_names);
                    let en = self.vname(Some(*end), block, extra_names);
                    let init = match rk {
                        ReduceKind::Sum | ReduceKind::Mean => "0.0f",
                        ReduceKind::Max => "-INFINITY",
                        ReduceKind::Min => "INFINITY",
                    };
                    let base_elem = if let Some(sec_src) = secondary_src {
                        let base_v = self.vname(*secondary_base, block, extra_names);
                        format!("float({src}[_i]) * float({sec_src}[_i - {base_v}])")
                    } else {
                        format!("float({src}[_i])")
                    };
                    let elem_expr = match transform.as_ref().map(|v| v.as_slice()) {
                        None | Some(&[]) => base_elem,
                        Some(ops) => {
                            let mut expr = base_elem;
                            for sub_op in ops {
                                expr = match sub_op {
                                    Op::UnaryOp { op, .. } => op.msl_emit(&expr),
                                    Op::Activation { kind, .. } =>
                                        format!("{}({})", kind.msl_fn(), expr),
                                    Op::Cast { dtype, .. } => self.emit_cast_expr(*dtype, &expr),
                                    Op::BinOp { op, rhs, .. } => {
                                        let rv = self.vname(Some(*rhs), block, extra_names);
                                        match op {
                                            BinOpKind::Mul => format!("({} * float({rv}))", expr),
                                            BinOpKind::Add => format!("({} + float({rv}))", expr),
                                            BinOpKind::Sub => format!("({} - float({rv}))", expr),
                                            BinOpKind::Div => format!("({} / float({rv}))", expr),
                                            _ => expr,
                                        }
                                    },
                                    _ => expr,
                                };
                            }
                            expr
                        },
                    };
                    let has_tid = matches!(kernel.mode, KernelMode::Reduction | KernelMode::Tile2D);
                    if has_tid {
                        let update = match rk {
                            ReduceKind::Sum | ReduceKind::Mean => format!("{v} += {elem_expr};"),
                            ReduceKind::Max => format!("{v} = max({v}, {elem_expr});"),
                            ReduceKind::Min => format!("{v} = min({v}, {elem_expr});"),
                        };
                        wl!(out, "{pad}float {v} = {init};");
                        wl!(out, "{pad}{{");
                        wl!(out, "{pad}    uint _sz   = {en} - {off};");
                        wl!(out, "{pad}    uint _full = _sz / (lsize * 4u);");
                        wl!(
                            out,
                            "{pad}    int  _xtra = (int)_sz - (int)(_full * lsize * 4u) - (int)(tid * 4u);"
                        );
                        wl!(out, "{pad}    if (_xtra >= 4) {{ _full++; _xtra = 0; }}");
                        wl!(out, "{pad}    uint _base = {off} + tid * 4u;");
                        wl!(
                            out,
                            "{pad}    for (uint _b = 0; _b < _full; _b++, _base += lsize * 4u) {{"
                        );
                        wl!(out, "{pad}        for (uint _k = 0; _k < 4u; _k++) {{");
                        wl!(out, "{pad}            uint _i = _base + _k;");
                        wl!(out, "{pad}            {update}");
                        wl!(out, "{pad}        }}");
                        wl!(out, "{pad}    }}");
                        wl!(out, "{pad}    for (int _k = 0; _k < _xtra; _k++) {{");
                        wl!(out, "{pad}        uint _i = _base + (uint)_k;");
                        wl!(out, "{pad}        {update}");
                        wl!(out, "{pad}    }}");
                        wl!(out, "{pad}}}");
                    } else {
                        let update = match rk {
                            ReduceKind::Sum | ReduceKind::Mean => format!("{v} += {elem_expr};"),
                            ReduceKind::Max => format!("{v} = max({v}, {elem_expr});"),
                            ReduceKind::Min => format!("{v} = min({v}, {elem_expr});"),
                        };
                        wl!(out, "{pad}float {v} = {init};");
                        wl!(out, "{pad}for (uint _i = {off}; _i < {en}; _i += {st}) {{");
                        wl!(out, "{pad}    {update}");
                        wl!(out, "{pad}}}");
                    }
                },

                Op::Reduce { value: val, axis, op: rk } => {
                    let v = self.vname(vid, block, extra_names);
                    let rv = self.vname(Some(*val), block, extra_names);
                    self.emit_reduce(out, &pad, &v, &rv, *axis, *rk, hoists, kernel);
                },

                Op::Cast { value, dtype } => {
                    let v = self.vname(vid, block, extra_names);
                    let rv = self.vname(Some(*value), block, extra_names);
                    let type_decl = self.msl_type_name(*dtype);
                    wl!(out, "{pad}{type_decl} {v} = {};", self.emit_cast_expr(*dtype, &rv));
                },

                // ---- control flow --------------------------------------
                Op::Loop { var, start, end, step, body: bid } => {
                    let s = self.vname(Some(*start), block, extra_names);
                    let e = self.vname(Some(*end), block, extra_names);
                    let st = self.vname(Some(*step), block, extra_names);
                    let vn = format!("i_{}", var.as_u32());
                    wl!(out, "{pad}for (uint {vn} = {s}; {vn} < {e}; {vn} += {st}) {{");
                    if let Some(bb) = all_blocks.get(bid) {
                        let loop_var_vid = ValueId::new(0xC000_0000 | var.as_u32());
                        let mut inner_names: BTreeMap<ValueId, String> =
                            block.names.iter().map(|(&k, v)| (k, format!("v_{v}"))).collect();
                        inner_names.extend(extra_names.iter().map(|(&k, v)| (k, v.clone())));
                        inner_names.insert(loop_var_vid, vn.clone());
                        inner_names.insert(ValueId::new(var.as_u32() + 1000), vn.clone());
                        self.emit_block(
                            bb,
                            all_blocks,
                            out,
                            indent + 1,
                            kernel,
                            type_env,
                            &inner_names,
                            hoists,
                        )?;
                    }
                    wl!(out, "{pad}}}");
                },

                // ---- escape hatch --------------------------------------
                Op::InlineMsl { source, inputs, outputs } => {
                    for (oi, slot) in outputs.iter().enumerate() {
                        let out_vid = vid.map(|v| ValueId::new(v.as_u32() + oi as u32));
                        let vn = self.vname(out_vid, block, extra_names);
                        wl!(out, "{pad}{} {vn};", self.msl_type_name(slot.dtype));
                    }
                    for (ii, inp_vid) in inputs.iter().enumerate() {
                        let inp = self.vname(Some(*inp_vid), block, extra_names);
                        wl!(out, "{pad}auto _in{ii} = {inp};");
                    }
                    for line in source.lines() {
                        wl!(out, "{pad}{line}");
                    }
                },

                // ---- fused elementwise chain ---------------------------
                Op::FusedElementwise { ops: fused_ops } => {
                    let v = self.vname(vid, block, extra_names);
                    if fused_ops.is_empty() {
                        wl!(out, "{pad}auto {v} = {{}};");
                    } else if let Some(resolved_vid) = vid {
                        let last_idx = fused_ops.len() - 1;
                        let expr = self.emit_fused_expr(
                            out,
                            &pad,
                            fused_ops,
                            block,
                            kernel,
                            type_env,
                            extra_names,
                            resolved_vid,
                            last_idx,
                        );
                        let result_is_bf16 = type_env
                            .get(&resolved_vid)
                            .map(|tv| tv.dtype == DType::BF16)
                            .unwrap_or(false);
                        if self.config.native_bfloat && result_is_bf16 {
                            wl!(out, "{pad}bfloat {v} = bfloat({expr});");
                        } else if result_is_bf16 {
                            let bf_type = self.msl_type_name(DType::BF16);
                            wl!(out, "{pad}{bf_type} {v} = {expr};");
                        } else {
                            wl!(out, "{pad}auto {v} = {expr};");
                        }
                    }
                },

                // ---- vectorised data movement ---------------------------
                Op::VectorLoad { src, byte_offset, len } => {
                    let v = self.vname(vid, block, extra_names);
                    let bo = self.vname(Some(*byte_offset), block, extra_names);
                    let param_dtype = kernel
                        .params
                        .iter()
                        .find(|p| p.name == *src)
                        .map(|p| p.dtype)
                        .unwrap_or(DType::F32);
                    let scalar_t = param_dtype.msl_name();
                    let vec_t: String = match (*len, param_dtype) {
                        (4, DType::F16) => "half4".into(),
                        (4, DType::F32) => "float4".into(),
                        (8, DType::F16) => "half8".into(),
                        (4, DType::BF16) if self.config.native_bfloat => "bfloat4".into(),
                        (2, DType::BF16) if self.config.native_bfloat => "bfloat2".into(),
                        (2, _) => format!("{}2", scalar_t),
                        (4, _) => format!("{}4", scalar_t),
                        _ => format!("{}4", scalar_t),
                    };
                    wl!(
                        out,
                        "{pad}{vec_t} {v} = *((device {vec_t}*)((device {scalar_t}*){src} + {bo}));"
                    );
                },

                Op::VectorStore { dst, byte_offset, len, value } => {
                    let rv = self.vname(Some(*value), block, extra_names);
                    let bo = self.vname(Some(*byte_offset), block, extra_names);
                    let param_dtype = kernel
                        .params
                        .iter()
                        .find(|p| p.name == *dst)
                        .map(|p| p.dtype)
                        .unwrap_or(DType::F32);
                    let scalar_t = param_dtype.msl_name();
                    let vec_t: String = match (*len, param_dtype) {
                        (4, DType::F16) => "half4".into(),
                        (4, DType::F32) => "float4".into(),
                        (8, DType::F16) => "half8".into(),
                        (4, DType::BF16) if self.config.native_bfloat => "bfloat4".into(),
                        (2, DType::BF16) if self.config.native_bfloat => "bfloat2".into(),
                        (2, _) => format!("{}2", scalar_t),
                        (4, _) => format!("{}4", scalar_t),
                        _ => format!("{}4", scalar_t),
                    };
                    wl!(
                        out,
                        "{pad}*((device {vec_t}*)((device {scalar_t}*){dst} + {bo})) = {vec_t}({rv});"
                    );
                },

                // ---- conditional branch ----------------------------------
                Op::If { cond, then_block: tbid, else_block } => {
                    let cv = self.vname(Some(*cond), block, extra_names);
                    wl!(out, "{pad}if ({cv}) {{");
                    let mut child_names: BTreeMap<ValueId, String> =
                        block.names.iter().map(|(&k, v)| (k, format!("v_{v}"))).collect();
                    child_names.extend(extra_names.iter().map(|(&k, v)| (k, v.clone())));
                    if let Some(tb) = all_blocks.get(tbid) {
                        self.emit_block(
                            tb,
                            all_blocks,
                            out,
                            indent + 1,
                            kernel,
                            type_env,
                            &child_names,
                            hoists,
                        )?;
                    }
                    if let Some(ebid) = else_block {
                        wl!(out, "{pad}}} else {{");
                        if let Some(eb) = all_blocks.get(ebid) {
                            self.emit_block(
                                eb,
                                all_blocks,
                                out,
                                indent + 1,
                                kernel,
                                type_env,
                                &child_names,
                                hoists,
                            )?;
                        }
                    }
                    wl!(out, "{pad}}}");
                },

                // ---- shape manipulation (zero-cost aliases) -------------
                Op::ExpandDims { value, .. } | Op::Reshape { value, .. } => {
                    let v = self.vname(vid, block, extra_names);
                    let rv = self.vname(Some(*value), block, extra_names);
                    wl!(out, "{pad}// ExpandDims/Reshape: same data, new indexing");
                    wl!(out, "{pad}auto {v} = {rv};");
                },

                Op::Cat { .. } => {
                    let v = self.vname(vid, block, extra_names);
                    wl!(out, "{pad}// Op::Cat: needs lowering pass");
                    wl!(out, "{pad}auto {v} = {{}};");
                },

                // ---- gather / scatter ------------------------------------
                Op::Gather { src, indices, .. } => {
                    let v = self.vname(vid, block, extra_names);
                    let iv = self.vname(Some(*indices), block, extra_names);
                    wl!(out, "{pad}// Op::Gather: indexed load from {src}");
                    wl!(out, "{pad}auto {v} = {src}[{iv}];");
                },

                Op::Scatter { dst, indices, value, .. } => {
                    let iv = self.vname(Some(*indices), block, extra_names);
                    let rv = self.vname(Some(*value), block, extra_names);
                    wl!(out, "{pad}// Op::Scatter: indexed store to {dst}");
                    wl!(out, "{pad}{dst}[{iv}] = {rv};");
                },

                // ---- atomics ----------------------------------------------
                Op::Atomic { op: ak, dst, index, value } => {
                    let iv = self.vname(Some(*index), block, extra_names);
                    let rv = self.vname(Some(*value), block, extra_names);
                    wl!(out, "{pad}{}({dst} + {iv}, {rv}, memory_order_relaxed);", ak.msl_fn());
                },

                // ---- tensor ops -------------------------------------------

                // ---- scan operations --------------------------------------
                Op::Scan { value, axis: _, op: rk, exclusive: _ } => {
                    let v = self.vname(vid, block, extra_names);
                    let rv = self.vname(Some(*value), block, extra_names);
                    let init = match rk {
                        ReduceKind::Sum | ReduceKind::Mean => "0.0f",
                        ReduceKind::Max => "-INFINITY",
                        ReduceKind::Min => "INFINITY",
                    };
                    wl!(out, "{pad}float {v} = {rv} + {init}; // Scan placeholder");
                },

                Op::StrideScan { dst, offset, end, .. } => {
                    let _off = self.vname(Some(*offset), block, extra_names);
                    let _en = self.vname(Some(*end), block, extra_names);
                    wl!(out, "{pad}// StrideScan: prefix sum over {dst}");
                    wl!(
                        out,
                        "{pad}auto {} = 0; // placeholder",
                        self.vname(vid, block, extra_names)
                    );
                },

                Op::StrideArgReduce { src, offset, end, op: _rk } => {
                    let v = self.vname(vid, block, extra_names);
                    let off = self.vname(Some(*offset), block, extra_names);
                    let en = self.vname(Some(*end), block, extra_names);
                    wl!(out, "{pad}float best_val = -INFINITY;");
                    wl!(out, "{pad}uint {v} = 0;");
                    wl!(out, "{pad}for (uint _i = {off}; _i < {en}; _i++) {{");
                    wl!(out, "{pad}    if ({src}[_i] > best_val) {{");
                    wl!(out, "{pad}        best_val = {src}[_i];");
                    wl!(out, "{pad}        {v} = _i;");
                    wl!(out, "{pad}    }}");
                    wl!(out, "{pad}}}");
                },

                Op::StrideStore { src, dst, offset, end, scalar, aux_src } => {
                    let off = self.vname(Some(*offset), block, extra_names);
                    let en = self.vname(Some(*end), block, extra_names);
                    let sc = self.vname(Some(*scalar), block, extra_names);
                    let has_tid = matches!(kernel.mode, KernelMode::Reduction | KernelMode::Tile2D);
                    if has_tid {
                        wl!(out, "{pad}{{");
                        wl!(out, "{pad}    uint _sz   = {en} - {off};");
                        wl!(out, "{pad}    uint _full = _sz / (lsize * 4u);");
                        wl!(
                            out,
                            "{pad}    int  _xtra = (int)_sz - (int)(_full * lsize * 4u) - (int)(tid * 4u);"
                        );
                        wl!(out, "{pad}    if (_xtra >= 4) {{ _full++; _xtra = 0; }}");
                        wl!(out, "{pad}    uint _base = {off} + tid * 4u;");
                        wl!(
                            out,
                            "{pad}    for (uint _b = 0; _b < _full; _b++, _base += lsize * 4u) {{"
                        );
                        wl!(out, "{pad}        for (uint _k = 0; _k < 4u; _k++) {{");
                        wl!(out, "{pad}            uint _i = _base + _k;");
                        if let Some(aux) = aux_src {
                            wl!(out, "{pad}            {dst}[_i] = {src}[_i] * {sc} * {aux}[_i];");
                        } else {
                            wl!(out, "{pad}            {dst}[_i] = {src}[_i] * {sc};");
                        }
                        wl!(out, "{pad}        }}");
                        wl!(out, "{pad}    }}");
                        wl!(out, "{pad}    for (int _k = 0; _k < _xtra; _k++) {{");
                        wl!(out, "{pad}        uint _i = _base + (uint)_k;");
                        if let Some(aux) = aux_src {
                            wl!(out, "{pad}        {dst}[_i] = {src}[_i] * {sc} * {aux}[_i];");
                        } else {
                            wl!(out, "{pad}        {dst}[_i] = {src}[_i] * {sc};");
                        }
                        wl!(out, "{pad}    }}");
                        wl!(out, "{pad}}}");
                    } else {
                        if let Some(aux) = aux_src {
                            wl!(
                                out,
                                "{pad}for (uint _i = {off}; _i < {en}; _i++) {dst}[_i] = {src}[_i] * {sc} * {aux}[_i];"
                            );
                        } else {
                            wl!(
                                out,
                                "{pad}for (uint _i = {off}; _i < {en}; _i++) {dst}[_i] = {src}[_i] * {sc};"
                            );
                        }
                    }
                },

                // ---- flash attention / sliding window attention ------------
                Op::FlashAttention { .. } | Op::SlidingWindowAttention { .. } => {
                    wl!(out, "{pad}// Attention: needs lowering pass");
                },

                // ---- high-level norms / mlp blocks -------------------------
                Op::RmsNorm { .. } | Op::GatedMlp { .. } => {
                    wl!(out, "{pad}// High-level op: needs lowering pass");
                },

                // ---- dequantize --------------------------------------------
                Op::Dequantize { .. } => {
                    wl!(out, "{pad}// Dequantize: needs lowering pass");
                },

                // ---- SIMD/threadgroup primitives ---------------------------
                Op::SimdReduce { value, op: rk } => {
                    let v = self.vname(vid, block, extra_names);
                    let rv = self.vname(Some(*value), block, extra_names);
                    match rk {
                        ReduceKind::Sum | ReduceKind::Mean =>
                            wl!(out, "{pad}float {v} = simd_sum(float({rv}));"),
                        ReduceKind::Max => wl!(out, "{pad}float {v} = simd_max(float({rv}));"),
                        ReduceKind::Min => wl!(out, "{pad}float {v} = simd_min(float({rv}));"),
                    }
                },

                Op::ThreadgroupAlloc { dtype, size, name } => {
                    let t = self.msl_type_name(*dtype);
                    hoists.push(format!("threadgroup {t} {name}[{size}];"));
                },

                Op::ThreadgroupLoad { name, index } => {
                    let v = self.vname(vid, block, extra_names);
                    let iv = self.vname(Some(*index), block, extra_names);
                    wl!(out, "{pad}auto {v} = {name}[{iv}];");
                },

                Op::ThreadgroupStore { name, index, value } => {
                    let iv = self.vname(Some(*index), block, extra_names);
                    let rv = self.vname(Some(*value), block, extra_names);
                    wl!(out, "{pad}{name}[{iv}] = {rv};");
                },

                Op::Barrier => {
                    wl!(out, "{pad}threadgroup_barrier(mem_flags::mem_threadgroup);");
                },

                // ---- mutable local variables ----------------------------
                Op::DeclareLocal { name, value } => {
                    let rv = self.vname(Some(*value), block, extra_names);
                    wl!(out, "{pad}auto __ml_{name} = {rv};");
                },

                Op::SetLocal { name, value } => {
                    let rv = self.vname(Some(*value), block, extra_names);
                    wl!(out, "{pad}__ml_{name} = {rv};");
                },

                // ---- arg reduce -----------------------------------------
                Op::ArgReduce { value, axis, op: rk } => {
                    let v = self.vname(vid, block, extra_names);
                    let rv = self.vname(Some(*value), block, extra_names);
                    wl!(out, "{pad}// ArgReduce(v{}, axis={axis}, {rk:?}): lowering needed", rv);
                    wl!(out, "{pad}auto {v} = 0;");
                },
            }
        }

        Ok(())
    }

    // ---- fused expression emission ---------------------------------------

    #[allow(clippy::too_many_arguments)]
    fn emit_fused_expr(
        &self,
        out: &mut String,
        pad: &str,
        fused_ops: &[Op],
        block: &Block,
        kernel: &Kernel,
        type_env: &TypeEnv,
        extra_names: &BTreeMap<ValueId, String>,
        resolved_vid: ValueId,
        idx: usize,
    ) -> String {
        

        let op = &fused_ops[idx];

        // For leaf ops with SUB_OP_FLAG operands, recurse.
        match op {
            Op::BinOp { op: kind, lhs, rhs } => {
                let l = self.fused_operand(
                    out,
                    pad,
                    fused_ops,
                    *lhs,
                    block,
                    kernel,
                    type_env,
                    extra_names,
                    resolved_vid,
                );
                let r = self.fused_operand(
                    out,
                    pad,
                    fused_ops,
                    *rhs,
                    block,
                    kernel,
                    type_env,
                    extra_names,
                    resolved_vid,
                );
                match kind {
                    BinOpKind::Max | BinOpKind::Min | BinOpKind::Pow =>
                        format!("{}({l}, {r})", kind.msl_symbol()),
                    BinOpKind::And => format!("({l} && {r})"),
                    BinOpKind::Or => format!("({l} || {r})"),
                    BinOpKind::Xor => format!("((bool){l} != (bool){r})"),
                    BinOpKind::BitAnd => format!("({l} & {r})"),
                    BinOpKind::BitOr => format!("({l} | {r})"),
                    BinOpKind::BitXor => format!("({l} ^ {r})"),
                    BinOpKind::Shl => format!("({l} << {r})"),
                    BinOpKind::Shr => format!("({l} >> {r})"),
                    _ => format!("({l} {} {r})", kind.msl_symbol()),
                }
            },
            Op::UnaryOp { op: kind, value } => {
                let v = self.fused_operand(
                    out,
                    pad,
                    fused_ops,
                    *value,
                    block,
                    kernel,
                    type_env,
                    extra_names,
                    resolved_vid,
                );
                kind.msl_emit(&v)
            },
            Op::Activation { kind, value } => {
                let v = self.fused_operand(
                    out,
                    pad,
                    fused_ops,
                    *value,
                    block,
                    kernel,
                    type_env,
                    extra_names,
                    resolved_vid,
                );
                format!("{}({v})", kind.msl_fn())
            },
            Op::Cast { dtype, value } => {
                let v = self.fused_operand(
                    out,
                    pad,
                    fused_ops,
                    *value,
                    block,
                    kernel,
                    type_env,
                    extra_names,
                    resolved_vid,
                );
                self.emit_cast_expr(*dtype, &v)
            },
            Op::Select { cond, on_true, on_false } => {
                let c = self.fused_operand(
                    out,
                    pad,
                    fused_ops,
                    *cond,
                    block,
                    kernel,
                    type_env,
                    extra_names,
                    resolved_vid,
                );
                let t = self.fused_operand(
                    out,
                    pad,
                    fused_ops,
                    *on_true,
                    block,
                    kernel,
                    type_env,
                    extra_names,
                    resolved_vid,
                );
                let f = self.fused_operand(
                    out,
                    pad,
                    fused_ops,
                    *on_false,
                    block,
                    kernel,
                    type_env,
                    extra_names,
                    resolved_vid,
                );
                format!("select({f}, {t}, bool({c}))")
            },
            Op::Broadcast { .. } => {
                // Broadcast in a fused chain is unusual; fall back.
                "0 /* broadcast-in-fused */".into()
            },
            _ => {
                let vid = op_to_vid(op);
                self.vname(Some(vid), block, extra_names)
            },
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn fused_operand(
        &self,
        out: &mut String,
        pad: &str,
        fused_ops: &[Op],
        vid: ValueId,
        block: &Block,
        kernel: &Kernel,
        type_env: &TypeEnv,
        extra_names: &BTreeMap<ValueId, String>,
        resolved_vid: ValueId,
    ) -> String {
        use crate::passes::fusion::SUB_OP_FLAG;
        if vid.as_u32() & SUB_OP_FLAG != 0 {
            let sub_idx = (vid.as_u32() & !SUB_OP_FLAG) as usize;
            if sub_idx < fused_ops.len() {
                self.emit_fused_expr(
                    out,
                    pad,
                    fused_ops,
                    block,
                    kernel,
                    type_env,
                    extra_names,
                    resolved_vid,
                    sub_idx,
                )
            } else {
                "0 /* bad sub-op ref */".into()
            }
        } else {
            self.vname(Some(vid), block, extra_names)
        }
    }

    // ---- variable naming -------------------------------------------------

    fn vname(
        &self,
        vid: Option<ValueId>,
        block: &Block,
        extra_names: &BTreeMap<ValueId, String>,
    ) -> String {
        let vid = match vid {
            Some(v) => v,
            None => return "_".into(),
        };
        if let Some(name) = extra_names.get(&vid) {
            return name.clone();
        }
        if let Some(hint) = block.names.get(&vid) {
            return format!("v_{hint}");
        }
        format!("v{}", vid.as_u32())
    }

    // ---- index expression emission ---------------------------------------

    fn emit_idx(
        &self,
        indices: &[IndexExpr],
        block: &Block,
        extra_names: &BTreeMap<ValueId, String>,
        kernel: &Kernel,
        src_or_dst: &str,
    ) -> String {
        let is_strided = kernel
            .params
            .iter()
            .any(|p| p.name == src_or_dst && matches!(p.kind, ParamKind::Strided));

        if is_strided {
            // Strided indexing: use shape/stride arrays for each dimension.
            // Emit index computation using named strides, e.g.:
            //   (v_row) * N + (v_col) * 1  (row-major, shape=[M,N])
            // The MSL compiler constant-folds the stride lookups.
            let parts: Vec<String> = indices
                .iter()
                .enumerate()
                .map(|(dim, ix)| {
                    let ix_str = self.idx_expr_str(ix, block, extra_names);
                    let stride = format!("{}_strides[{dim}]", src_or_dst);
                    format!("({ix_str}) * {stride}")
                })
                .collect();
            parts.join(" + ")
        } else if indices.len() == 1 {
            self.idx_expr_str(&indices[0], block, extra_names)
        } else {
            // Multi-dim into flat: N is first stride, 1 is last stride.
            let param = kernel.params.iter().find(|p| p.name == src_or_dst);
            let shape = param.map(|p| &p.shape);
            let stride1 =
                shape.and_then(|s| s.dim(1)).map(dim_to_msl_str).unwrap_or("1".into());
            let mut offset = String::new();
            for (dim, ix) in indices.iter().enumerate() {
                let ix_str = self.idx_expr_str(ix, block, extra_names);
                if dim == 0 {
                    offset.push_str(&format!("({ix_str}) * {stride1}"));
                } else {
                    offset.push_str(&format!(" + ({ix_str})"));
                }
            }
            offset
        }
    }

    fn idx_expr_str(
        &self,
        ix: &IndexExpr,
        block: &Block,
        extra_names: &BTreeMap<ValueId, String>,
    ) -> String {
        match ix {
            IndexExpr::Value(v) => self.vname(Some(*v), block, extra_names),
            IndexExpr::Const(n) => n.to_string(),
            IndexExpr::Range(v, _) => self.vname(Some(*v), block, extra_names),
        }
    }

    fn shape_nelems_str(&self, shape: &Shape) -> String {
        shape.num_elements().map(|n| n.to_string()).unwrap_or_else(|| {
            let rank = shape.rank();
            (0..rank)
                .filter_map(|i| shape.dim(i))
                .map(dim_to_msl_str)
                .collect::<Vec<_>>()
                .join(" * ")
        })
    }

    fn emit_tile_alloc(
        &self,
        dtype: &DType,
        shape: &Shape,
        name: &str,
        fill: f64,
    ) -> (String, Vec<String>) {
        let t = self.msl_type_name(*dtype);
        let n = self.shape_nelems_str(shape);
        let decl = format!("{t} {name}[{n}]");
        let init = if fill == 0.0 {
            vec![format!("for (uint _i = 0; _i < {n}; _i++) {name}[_i] = 0;")]
        } else {
            vec![format!("for (uint _i = 0; _i < {n}; _i++) {name}[_i] = {fill};")]
        };
        (decl, init)
    }
}

// ---- helpers ------------------------------------------------------------

fn op_to_vid(op: &Op) -> ValueId {
    match op {
        Op::ProgramId { .. } => ValueId::new(0),
        Op::Const { value } => ValueId::new(*value as u32),
        _ => ValueId::new(0),
    }
}

impl Default for MslGenerator {
    fn default() -> Self { MslGenerator::new(MslConfig::default()) }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use metaltile_core::{
        dtype::DType,
        ir::{BinOpKind, IndexExpr, Kernel, Op, Param, ValueId},
        shape::Shape,
    };

    use super::*;

    fn make_vadd() -> Kernel {
        let mut k = Kernel::new("vector_add");
        k.params.push(Param {
            name: "a".into(),
            dtype: DType::F32,
            shape: Shape::scalar(),
            is_output: false,
            kind: Default::default(),
        });
        k.params.push(Param {
            name: "b".into(),
            dtype: DType::F32,
            shape: Shape::scalar(),
            is_output: false,
            kind: Default::default(),
        });
        k.params.push(Param {
            name: "c".into(),
            dtype: DType::F32,
            shape: Shape::scalar(),
            is_output: true,
            kind: Default::default(),
        });
        k.body.push_op(Op::ProgramId { axis: 0 }, ValueId::new(0));
        k.body.name_value(ValueId::new(0), "idx");
        k.body.push_op(
            Op::Load {
                src: "a".into(),
                mask: None,
                other: None,
                indices: vec![IndexExpr::Value(ValueId::new(0))],
            },
            ValueId::new(1),
        );
        k.body.name_value(ValueId::new(1), "x");
        k.body.push_op(
            Op::Load {
                src: "b".into(),
                mask: None,
                other: None,
                indices: vec![IndexExpr::Value(ValueId::new(0))],
            },
            ValueId::new(2),
        );
        k.body.name_value(ValueId::new(2), "y");
        k.body.push_op(
            Op::BinOp { op: BinOpKind::Add, lhs: ValueId::new(1), rhs: ValueId::new(2) },
            ValueId::new(3),
        );
        k.body.name_value(ValueId::new(3), "sum");
        k.body.push_op_no_result(Op::Store {
            mask: None,
            dst: "c".into(),
            indices: vec![IndexExpr::Value(ValueId::new(0))],
            value: ValueId::new(3),
        });
        k
    }

    #[test]
    fn vadd_msl_structure() {
        let k = make_vadd();
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(msl.contains("kernel void vector_add"), "missing kernel declaration");
        assert!(msl.contains("const device float *a [[buffer(0)]]"), "missing param a");
        assert!(msl.contains("const device float *b [[buffer(1)]]"), "missing param b");
        assert!(msl.contains("device float *c [[buffer(2)]]"), "missing output param c");
        assert!(msl.contains("uint tid [[thread_position_in_grid]]"), "missing scalar tid");
        assert!(!msl.contains("tid.x"), "scalar kernel must not use tid.x");
    }

    #[test]
    fn vadd_msl_load_store() {
        let k = make_vadd();
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(msl.contains("v_idx"), "program_id should map to tid");
        assert!(msl.contains("a[v_idx]"), "load from a at idx");
        assert!(msl.contains("b[v_idx]"), "load from b at idx");
        assert!(msl.contains("v_x + v_y"), "add x and y");
        assert!(msl.contains("c[v_idx] = v_sum"), "store sum to c");
    }

    #[test]
    fn const_op_emits_int_literal() {
        let mut k = Kernel::new("const_test");
        k.body.push_op(Op::Const { value: 42 }, ValueId::new(0));
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(msl.contains("int v0 = 42"), "Const op should emit int literal");
    }

    #[test]
    fn cast_op_emits_static_cast() {
        let mut k = Kernel::new("cast_test");
        k.body.push_op(Op::Const { value: 1 }, ValueId::new(0));
        k.body.push_op(Op::Cast { value: ValueId::new(0), dtype: DType::F16 }, ValueId::new(1));
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(msl.contains("static_cast<half>"), "cast to f16 should use static_cast<half>");
    }

    #[test]
    fn native_bfloat_omits_compat_preamble() {
        let mut k = Kernel::new("native_bfloat_param");
        k.params.push(Param {
            name: "a".into(),
            dtype: DType::BF16,
            shape: Shape::scalar(),
            is_output: false,
            kind: Default::default(),
        });
        let msl = MslGenerator::new(MslConfig { native_bfloat: true, ..MslConfig::default() })
            .generate(&k)
            .unwrap();
        assert!(
            !msl.contains("struct bfloat16_t"),
            "native bfloat mode must not emit the compatibility preamble"
        );
        assert!(
            msl.contains("const device bfloat *a [[buffer(0)]]"),
            "native bfloat mode should keep native buffer types"
        );
    }

    #[test]
    fn bf16_cast_uses_compat_ctor_when_native_bfloat_disabled() {
        let mut k = Kernel::new("compat_bf16_cast");
        k.body.push_op(Op::Const { value: 1 }, ValueId::new(0));
        k.body.push_op(Op::Cast { value: ValueId::new(0), dtype: DType::BF16 }, ValueId::new(1));
        let msl = MslGenerator::new(MslConfig { native_bfloat: false, ..MslConfig::default() })
            .generate(&k)
            .unwrap();
        assert!(msl.contains("struct bfloat16_t"), "compat mode should emit the bfloat16_t helper");
        assert!(
            msl.contains("bfloat16_t v1 = bfloat16_t(v0);"),
            "compat mode should cast to the compatibility struct"
        );
    }

    #[test]
    fn bf16_cast_uses_native_static_cast_when_enabled() {
        let mut k = Kernel::new("native_bf16_cast");
        k.body.push_op(Op::Const { value: 1 }, ValueId::new(0));
        k.body.push_op(Op::Cast { value: ValueId::new(0), dtype: DType::BF16 }, ValueId::new(1));
        let msl = MslGenerator::new(MslConfig { native_bfloat: true, ..MslConfig::default() })
            .generate(&k)
            .unwrap();
        assert!(
            !msl.contains("struct bfloat16_t"),
            "native mode should not emit the compatibility helper"
        );
        assert!(
            msl.contains("bfloat v1 = bfloat(v0);"),
            "native mode should cast directly to bfloat via constructor"
        );
    }

    #[test]
    fn unary_op_emit() {
        use metaltile_core::ir::UnaryOpKind;
        let mut k = Kernel::new("unary_test");
        k.body.push_op(Op::Const { value: 1 }, ValueId::new(0));
        k.body
            .push_op(Op::UnaryOp { op: UnaryOpKind::Exp, value: ValueId::new(0) }, ValueId::new(1));
        k.body.name_value(ValueId::new(1), "r");
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(msl.contains("exp(v0)"), "exp unary op");
        assert!(msl.contains("v_r"), "named result");
    }

    #[test]
    fn activation_silu_emits_helper() {
        use metaltile_core::ir::ActKind;
        let mut k = Kernel::new("silu_test");
        k.body.push_op(Op::Const { value: 1 }, ValueId::new(0));
        k.body.push_op(
            Op::Activation { kind: ActKind::Silu, value: ValueId::new(0) },
            ValueId::new(1),
        );
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(msl.contains("mt_silu"), "silu helper function name");
        assert!(msl.contains("inline T mt_silu"), "silu helper definition");
    }

    #[test]
    fn select_emit() {
        let mut k = Kernel::new("select_test");
        k.body.push_op(Op::Const { value: 1 }, ValueId::new(0));
        k.body.push_op(Op::Const { value: 2 }, ValueId::new(1));
        k.body.push_op(Op::Const { value: 3 }, ValueId::new(2));
        k.body.push_op(
            Op::Select {
                cond: ValueId::new(0),
                on_true: ValueId::new(1),
                on_false: ValueId::new(2),
            },
            ValueId::new(3),
        );
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(msl.contains("select("), "select call");
        assert!(msl.contains("bool("), "bool cast on condition");
    }

    #[test]
    fn multi_dim_load_stride() {
        use metaltile_core::{constexpr::ConstExpr, shape::Dim};
        let mut k = Kernel::new("matload_test");
        let m_ce = ConstExpr::new("M");
        let n_ce = ConstExpr::new("N");
        k.params.push(Param {
            name: "a".into(),
            dtype: DType::F32,
            shape: Shape::new([Dim::ConstExpr(m_ce.clone()), Dim::ConstExpr(n_ce.clone())]),
            is_output: false,
            kind: Default::default(),
        });
        k.params.push(Param {
            name: "out".into(),
            dtype: DType::F32,
            shape: Shape::scalar(),
            is_output: true,
            kind: Default::default(),
        });
        k.constexprs.push(metaltile_core::ir::ConstExprDecl {
            name: m_ce,
            dtype: DType::U32,
            value: None,
        });
        k.constexprs.push(metaltile_core::ir::ConstExprDecl {
            name: n_ce,
            dtype: DType::U32,
            value: None,
        });
        k.body.push_op(Op::Const { value: 0 }, ValueId::new(0));
        k.body.name_value(ValueId::new(0), "row");
        k.body.push_op(Op::Const { value: 0 }, ValueId::new(1));
        k.body.name_value(ValueId::new(1), "col");
        k.body.push_op(
            Op::Load {
                mask: None,
                other: None,
                src: "a".into(),
                indices: vec![IndexExpr::Value(ValueId::new(0)), IndexExpr::Value(ValueId::new(1))],
            },
            ValueId::new(2),
        );
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(msl.contains("(v_row) * N + (v_col)"), "2D load must use row-major stride");
    }

    #[test]
    fn fusion_cast_exp_binop_into_single_expression() {
        use metaltile_core::ir::{BinOpKind, UnaryOpKind};

        use crate::passes::{Pass, fusion::FusionPass};

        let mut k = Kernel::new("fused_test");
        k.body.push_op(Op::Const { value: 3 }, ValueId::new(0));
        k.body.push_op(Op::Cast { value: ValueId::new(0), dtype: DType::F32 }, ValueId::new(1));
        k.body
            .push_op(Op::UnaryOp { op: UnaryOpKind::Exp, value: ValueId::new(1) }, ValueId::new(2));
        k.body.push_op(Op::Const { value: 2 }, ValueId::new(3));
        k.body.push_op(
            Op::BinOp { op: BinOpKind::Mul, lhs: ValueId::new(2), rhs: ValueId::new(3) },
            ValueId::new(4),
        );
        FusionPass.run(&mut k).unwrap();
        let has_fused = k.body.ops.iter().any(|op| matches!(op, Op::FusedElementwise { .. }));
        assert!(has_fused, "fusion pass should create a FusedElementwise op");
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(
            msl.contains("exp") && msl.contains(" * "),
            "fused expression should contain exp and mul"
        );
        let lines: Vec<&str> = msl.lines().collect();
        let fused_line = lines.iter().find(|l| l.contains("v4")).unwrap();
        assert!(
            fused_line.contains("exp") && fused_line.contains("static_cast"),
            "single fused line should contain both exp and cast: {}",
            fused_line
        );
        assert!(!msl.contains("v1 = "), "no separate declaration for v1");
        assert!(!msl.contains("v2 = "), "no separate declaration for v2");
    }
}
